//
//  LXEmiiterLayerChainModel.m
//  LXCategory
//
//  Created by 麻小亮 on 2019/1/4.
//  Copyright © 2019 xllpp. All rights reserved.
//

#import "LXEmiiterLayerChainModel.h"
#define LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(LXMethod,LXParaType) LXCATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(LXMethod,LXParaType, LXEmiiterLayerChainModel *, CAEmitterLayer)

@implementation LXEmiiterLayerChainModel
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterCells, NSArray<CAEmitterCell *> *)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(birthRate, float)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(lifetime, float)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterPosition, CGPoint)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterZPosition, CGFloat)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterSize, CGSize)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterDepth, CGFloat)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterShape, CAEmitterLayerEmitterShape)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(emitterMode, CAEmitterLayerEmitterMode)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(renderMode, CAEmitterLayerRenderMode)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(preservesDepth, BOOL)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(velocity, float)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(scale, float)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(spin, float)
LXCATEGORY_CHAIN_EMITTERLAYER_IMPLEMENTATION(seed, unsigned int)
@end
LXCATEGORY_LAYER_IMPLEMENTATION(CAEmitterLayer, LXEmiiterLayerChainModel)
