//
//  LXShaperLayerChainModel.m
//  LXCategory
//
//  Created by 麻小亮 on 2019/1/4.
//  Copyright © 2019 xllpp. All rights reserved.
//

#import "LXShaperLayerChainModel.h"
#define LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(LXMethod,LXParaType) LXCATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(LXMethod,LXParaType, LXShaperLayerChainModel *, CAShapeLayer)

@implementation LXShaperLayerChainModel
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(path, CGPathRef)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(fillColor, CGColorRef)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(fillRule, CAShapeLayerFillRule)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(strokeColor, CGColorRef)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(strokeStart, CGFloat)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(strokeEnd, CGFloat)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineWidth, CGFloat)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(miterLimit, CGFloat)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineCap, CAShapeLayerLineCap)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineJoin, CAShapeLayerLineJoin)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineDashPhase, CGFloat)
LXCATEGORY_CHAIN_SHAPERLAYER_IMPLEMENTATION(lineDashPattern, NSArray<NSNumber *> *)
@end
LXCATEGORY_LAYER_IMPLEMENTATION(CAShapeLayer, LXShaperLayerChainModel)
