//
//  LXTextLayerChainModel.m
//  LXCategory
//
//  Created by 麻小亮 on 2019/1/4.
//  Copyright © 2019 xllpp. All rights reserved.
//

#import "LXTextLayerChainModel.h"
#define LXCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(LXMethod,LXParaType) LXCATEGORY_CHAIN_LAYERCLASS_IMPLEMENTATION(LXMethod,LXParaType, LXTextLayerChainModel *, CATextLayer)

@implementation LXTextLayerChainModel
LXCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(string, id)
LXCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(font, CFTypeRef)
LXCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(fontSize, CGFloat)
LXCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(foregroundColor, CGColorRef)
LXCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(wrapped, BOOL)
LXCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(truncationMode, CATextLayerTruncationMode)
LXCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(alignmentMode, CATextLayerAlignmentMode)
LXCATEGORY_CHAIN_TEXTLAYER_IMPLEMENTATION(allowsFontSubpixelQuantization, BOOL)

@end
LXCATEGORY_LAYER_IMPLEMENTATION(CATextLayer, LXTextLayerChainModel)
