//
//  LXTextViewChainModel.m
//  LXCategory
//
//  Created by 麻小亮 on 2018/12/27.
//  Copyright © 2018 xllpp. All rights reserved.
//

#import "LXTextViewChainModel.h"
#define LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(LXMethod,LXParaType) LXCATEGORY_CHAIN_VIEWCLASS_IMPLEMENTATION(LXMethod,LXParaType, LXTextViewChainModel *,UITextView)
@implementation LXTextViewChainModel
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(delegate, id<UITextViewDelegate>);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(text, NSString *);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(font, UIFont *);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textColor, UIColor *);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textAlignment, NSTextAlignment);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(selectedRange, NSRange);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(editable, BOOL);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(selectable, BOOL);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(dataDetectorTypes, UIDataDetectorTypes);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(keyboardType, UIKeyboardType);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(allowsEditingTextAttributes, BOOL);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(attributedText, NSAttributedString *);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(typingAttributes, NSDictionary *);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(clearsOnInsertion, BOOL);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textContainerInset, UIEdgeInsets);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(linkTextAttributes, NSDictionary *);

#pragma mark - UITextInputTraits -
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(autocapitalizationType, UITextAutocapitalizationType);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(autocorrectionType, UITextAutocorrectionType)
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(spellCheckingType, UITextSpellCheckingType)
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(smartQuotesType, UITextSmartQuotesType)
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(smartInsertDeleteType, UITextSmartInsertDeleteType)
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(smartDashesType, UITextSmartDashesType);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(keyboardAppearance, UIKeyboardAppearance);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(returnKeyType, UIReturnKeyType);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(enablesReturnKeyAutomatically, BOOL);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(secureTextEntry, BOOL);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(textContentType, UITextContentType);
LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION(passwordRules, UITextInputPasswordRules *);
@end
LXCATEGORY_VIEW_IMPLEMENTATION(UITextView, LXTextViewChainModel)

#undef LXCATEGORY_CHAIN_TEXT_IMPLEMENTATION
